name: Run Script Daily

on:
  schedule:
    # Cron expression to run daily at 16:36 UTC (equivalent to 17:36 CET)
    - cron: "36 16 * * *"
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # You can specify a more specific version like '3.8' or '3.9'

      - name: Install dependencies
        run: |
          # Ensure you have a requirements.txt file in your repo, or handle missing requirements
          pip install -r req.txt || echo "No dependencies to install."

      - name: Run Python script
        env:
          apikey: ${{ secrets.APIKEY }}  # Use your custom API key secret here
        run: python incremental_import.py  # Ensure 'incremental_import.py' exists in the repo

      - name: Configure Git
        run: |
          git config --global user.name "zp"
          git config --global user.email "your-email@example.com"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided token to authenticate
